### ISSUE TITLE
I wanted to question some commands

### ISSUE THREAD

**Issue by Leotaku-senpai** [ImKKingshuk/BloatwareHatao#2]
Edited: I was really stressed so I'm going to redo it So there are a lot of unnecessary things that are not in pro mode and that you could add, so I will explain to you, for example, the Daemon was not removed in pro mode, which doesn't make sense because it is a "Spying" application and the ultra mode remove this so I wanted to give you an idea, you could put the pro mode as an ultra mode but not removing the essential part of the miui/hyperos type Cleaning and game mode and security like the applications everyone uses And leave the ultra mode how is it for people who really want to remove everything from miui/hyperos. I want you to understand that this would be really good for me and other people who don't want to do additional commands like me :) Edited again ahhh I wanted to highlight what you could leave to improve like things like game mode, cleaning, safe mode and themes etc... Everything that the normal user who doesn't like bloatware would use every day

**Comment by ImKKingshuk** [comment]
**HyperOS Daemon** is integrated with the system core framework, if you remove it you may end up with bootloop issues etc which is not recommended for a user,  only if the user unlocked  bootloader or rooted device, then its good , you can flash the ROMs or just fix it with some Modules, that's why I didn't added the Daemon in Pro mode, instead added in Ultra mode.
